var countryData = [
  //ISO Code [0]
  { 
    "Spain": "ES",
    "Estonia": "EE",
    "Portugal": "PT",
    "Austria": "AT",
    "Iceland": "IS",
    "Finland": "FI",
    "Cyprus": "CY",
    "EU (27 countries)": null,
    "Sweden": "SE",
    "Slovenia": "SI",
    "Romania": "RO",
    "Bulgaria": "BG",
    "Hungary": "HU",
    "EU (25 countries)": null,
    "United Kingdom": "GB",
    "Italy": "IT",
    "France": "FR",
    "Belgium": "BE",
    "Slovakia": "SK",
    "Latvia": "LV",
    "Greece": "GR",
    "Malta": "MT",
    "Lithuania": "LT",
    "Norway": "NO",
    "Denmark": "DK",
    "Netherlands": "NL",
    "Ireland": "IE",
    "Czech Republic": "CZ",
    "Euro area (17 countries)": null,
    "Poland": "PL",
    "Luxembourg": "LU",
    "Germany": "DE",
    "Euro area (16 countries)": null
  },
  //Deficit 2010 [1]
  {
    "Spain": -9.3,
    "Estonia": 0.2,
    "Portugal": -9.8,
    "Austria": -4.4,
    "Iceland": -10.1,
    "Finland": -2.5,
    "Cyprus": -5.3,
    "EU (27 countries)": -6.6,
    "Sweden": 0.2,
    "Slovenia": -5.8,
    "Romania": -6.9,
    "Bulgaria": -3.1,
    "Hungary": -4.2,
    "EU (25 countries)": -6.6,
    "United Kingdom": -10.3,
    "Italy": -4.6,
    "France": -7.1,
    "Belgium": -4.1,
    "Slovakia": -7.7,
    "Latvia": -8.3,
    "Greece": -10.6,
    "Malta": -3.6,
    "Lithuania": -7,
    "Norway": 10.6,
    "Denmark": -2.6,
    "Netherlands": -5.1,
    "Ireland": -31.3,
    "Czech Republic": -4.8,
    "Euro area (17 countries)": -6.2,
    "Poland": -7.8,
    "Luxembourg": -1.1,
    "Germany": -4.3,
    "Euro area (16 countries)": -6.3
  },
  // Bond Yields [2]
  { 
    "Spain": 5.26,
    "Estonia": null,
    "Portugal": 11.72,
    "Austria": 2.92,
    "Iceland": null,
    "Finland": 2.51,
    "Cyprus": 7,
    "EU (27 countries)": 4.08,
    "Sweden": 1.9,
    "Slovenia": 5.16,
    "Romania": 7.48,
    "Bulgaria": 5.26,
    "Hungary": 7.88,
    "EU (25 countries)": null,
    "United Kingdom": 2.52,
    "Italy": 5.97,
    "France": 2.99,
    "Belgium": 4.2,
    "Slovakia": 4.33,
    "Latvia": 5.62,
    "Greece": 18.04,
    "Malta": 4.26,
    "Lithuania": 5.05,
    "Norway": null,
    "Denmark": 2.23,
    "Netherlands": 2.46,
    "Ireland": 8.1,
    "Czech Republic": 3.14,
    "Euro area (17 countries)": null,
    "Poland": 5.71,
    "Luxembourg": 2.37,
    "Germany": 2,
    "Euro area (16 countries)": null
  },
  // Debt 2011 [3]
  {
    "Spain": 65.2,
    "Estonia": 6.2,
    "Portugal": 106.3,
    "Austria": 72.5,
    "Iceland": null,
    "Finland": 45.3,
    "Cyprus": 66.8,
    "EU (27 countries)": 80.9,
    "Sweden": 36.8,
    "Slovenia": 44.4,
    "Romania": 34.3,
    "Bulgaria": 15.2,
    "Hungary": 76.8,
    "EU (25 countries)": null,
    "United Kingdom": 80.1,
    "Italy": 121.4,
    "France": 86.1,
    "Belgium": 98.4,
    "Slovakia": 42.5,
    "Latvia": 45.2,
    "Greece": 151.9,
    "Malta": 71.6,
    "Lithuania": 37.9,
    "Norway": 42.3,
    "Denmark": 47.5,
    "Netherlands": 63.8,
    "Ireland": 104.6,
    "Czech Republic": 40.1,
    "Euro area (17 countries)": 87.3,
    "Poland": 56,
    "Luxembourg": 18.7,
    "Germany": 81.1,
    "Euro area (16 countries)": 87.4
  },
  // Unemployment [4]
  {
    "Spain": 22.6,
    "Estonia": 12.8,
    "Portugal": 12.5,
    "Austria": 3.9,
    "Iceland": null,
    "Finland": 7.8,
    "Cyprus": 7.8,
    "EU (27 countries)": 9.7,
    "Sweden": 7.2,
    "Slovenia": 8,
    "Romania": 7.5,
    "Bulgaria": 11.9,
    "Hungary": 9.9,
    "EU (25 countries)": null,
    "United Kingdom": 8.1,
    "Italy": 8.3,
    "France": 9.9,
    "Belgium": 6.7,
    "Slovakia": 13.5,
    "Latvia": 16.1,
    "Greece": 17.6,
    "Malta": 6.6,
    "Lithuania": 15.5,
    "Norway": 3.2,
    "Denmark": 7.1,
    "Netherlands": 4.5,
    "Ireland": 14.2,
    "Czech Republic": 6.6,
    "Euro area (17 countries)": 10.2,
    "Poland": 9.4,
    "Luxembourg": 4.8,
    "Germany": 5.8,
    "Euro area (16 countries)": 10.2
  },
  // Youth Unemployment (15-24) [6]
  {
    "Spain": 48,
    "Estonia": 21.8,
    "Portugal": 27.1,
    "Austria": 7.1,
    "Iceland": null,
    "Finland": 20.4,
    "Cyprus": 22.6,
    "EU (27 countries)": 21.4,
    "Sweden": 22.1,
    "Slovenia": 13.4,
    "Romania": 22.8,
    "Bulgaria": 26.8,
    "Hungary": 23.1,
    "EU (25 countries)": null,
    "United Kingdom": 21.2,
    "Italy": 29.3,
    "France": 24,
    "Belgium": 17.4,
    "Slovakia": 30.7,
    "Latvia": 29.7,
    "Greece": 43.4,
    "Malta": 15.3,
    "Lithuania": 32.7,
    "Norway": 8.2,
    "Denmark": 13.9,
    "Netherlands": 8,
    "Ireland": 29.5,
    "Czech Republic": 18.8,
    "Euro area (17 countries)": 21.2,
    "Poland": 23.8,
    "Luxembourg": 14.7,
    "Germany": 9.2,
    "Euro area (16 countries)": 21.2
  }
];